### ISSUE TITLE
hi,InkedCurtis

### ISSUE THREAD

**Issue by vinch1n** [InkedCurtis/FUT-API#1]
thanks for sharing,but  it seems unfinished.
 are you still working on it?

**Comment by InkedCurtis** [comment]
Hi @vinch1n, in what way do you mean it's unfinished?

**Comment by vinch1n** [comment]
some part of code run error , here are some i found,

1. need composer to require GuzzleHttp
2. $items = $fut->searchAuctions('player'); this function name should be  'search' ,wrong in README.md.
3. 'search' function must fill all parameter to search players .
4. $events = $this->pin->event('page_view', 'Transfer Market Search');
    $this->pin->send(**$events**);
    parameter missing
5. 'use Config'  code like this  must require file first. 

after fixed all those things above,i have already successfully logged in and searched out players.
thanks,InkedCurtis.

**Comment by InkedCurtis** [comment]
Thankyou, fixed & updated files.
