### ISSUE TITLE
player database fifa 19

### ISSUE THREAD

**Issue by futseller** [InkedCurtis/FUT-API#17]
Hello! Where can I get the current player database? and is it possible to get images to each of them?

**Comment by InkedCurtis** [comment]
URL: https://fifa19.content.easports.com/fifa/fltOnlineAssets/7D49A6B1-760B-4491-B10C-167FBC81D58A/2019/fut/items/web/players.json

```
players[i['id']] = {
    'id': i['id'],
    'firstname': i['f'],
    'lastname': i['l'],
    'surname': i.get('c'),
    'rating': i['r']
}
```
