### ISSUE TITLE
error GuzzleHttp

### ISSUE THREAD

**Issue by matiborr** [InkedCurtis/FUT-API#2]
Fatal error: Class 'GuzzleHttp\Client' not found in /Applications/XAMPP/xamppfiles/htdocs/fut/Core.php on line 30

When I try to execute the script, does that error happen to me?
sorry for my english

**Comment by vinch1n** [comment]
do you  have composer?
if not,you should install composer first then follow guide to require 'GuzzleHttp'

**Comment by matiborr** [comment]
Warning: 



file_put_contents(/Applications/XAMPP/xamppfiles/htdocs/fut/cookies/YXBwc3dpcG9rQGdtYWlsLmNvbQ==): failed to open stream: No such file or directory in /Applications/XAMPP/xamppfiles/htdocs/fut/vendor/guzzlehttp/guzzle/src/Cookie/FileCookieJar.php on line 59


I could fix the problem. What can this error be?

**Comment by vinch1n** [comment]
this problem is more simple, you can just create 'cookies' directory in your web root directory,and make it writable.

**Comment by matiborr** [comment]
Warning: curl_exec(): Unable to create temporary file, Check permissions in temporary files directory. in /Applications/XAMPP/xamppfiles/htdocs/fut/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php on line 40

Fatal error: Uncaught exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 23: Failed writing body (723 != 12120) (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in /Applications/XAMPP/xamppfiles/htdocs/fut/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:187 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/fut/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 /Applications/XAMPP/xamppfiles/htdocs/fut/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #2 /Applications/XAMPP/xamppfiles/htdocs/fut/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #3 in /Applications/XAMPP/xamppfiles/htdocs/fut/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 187




like that keeps coming out, thanks for the previous help

**Comment by vinch1n** [comment]
have you made the ‘cookies’ directory writable??

**Comment by matiborr** [comment]
Yes, i did!

![image](https://user-images.githubusercontent.com/18429022/33745961-c2453b46-db98-11e7-93dd-0bedcfe1f366.png)

**Comment by vinch1n** [comment]
hmm...
that would be a problem
something sure is permission issue

**Comment by matiborr** [comment]
Fatal error: Call to undefined method Core::searchAuctions() in /home/teprende/public_html/fut/prueba.php on line 8


I was able to solve the problem. But I can not find this method. How do I look for players?

**Comment by vinch1n** [comment]
dude, see another issue in this repo that post by me.
