### ISSUE TITLE
Search lowest price players

### ISSUE THREAD

**Issue by matiborr** [InkedCurtis/FUT-API#3]
When I try to search with max_buy <8k the bot doesn't find any result 

![image](https://user-images.githubusercontent.com/18429022/33751375-3e962848-dbb9-11e7-9594-6df5b12c3ad7.png)

**Comment by InkedCurtis** [comment]
Are you sure their is cards listed on the market for less than 8k for your specified player?

**Comment by matiborr** [comment]
I want to bring buy a player under 8 thousand of a league, can I do that?

**Comment by matiborr** [comment]
can you help me?

**Comment by matiborr** [comment]
Could you help me?

**Comment by Samclay8** [comment]
I'm not sure optional parameters are working for search? 
$items = $fut->searchAuctions('player', 'bronze')
I'm not getting any result.

**Comment by matiborr** [comment]
No puedo encontrar jugadores por precios bajos. Utilizando el parámetro max_buy a menos de 8000 no se encuentra nada. ¿Puede pasarme una consulta para encontrar jugadores a bajo precio?

@Samclay8 @InkedCurtis

**Comment by InkedCurtis** [comment]
Fixed.
