### ISSUE TITLE
APIs Postman's Collection

### ISSUE THREAD

**Issue by soikmd2** [InkedCurtis/FUT-API#4]
Hello @InkedCurtis! First of all, nice work with this!

If it's not asking too much, could you save requests in a Postman's collection and share it with us?

Would be great for those who don't have any front-end skills.

Thanks in advance! And.. please keep this job going ;)

**Comment by InkedCurtis** [comment]
Hi,

Currently I don't have time to do so, but what you can do is add a Middleware to the Guzzle client to save a copy of all requests to a text document.
